export const CONSTANTS = {
    HEADER: "Cropper",
    DROP_HERE: "Drag and drop a file here, or click to select a file",
    CUSTOM_CROP: 'Click on the image and drag to Custom crop the image',
    PREVIEW: "Preview Canvas Crop",
    DOWNLOAD: "Download",
    HOME: 'Add New Image',
    VIEW: 'Uploaded Images',
    CUSTOM_CROP_PREVIEW: 'Custom Crop',
    HORIZONTAL: 'Horizontal Crop - 755 X 450',
    VERTICAL: 'Vertical Crop - 365 X 450',
    HORIZONTAL_SMALL: 'Horizontal Small - 365 X 212',
    GALLERY: 'Gallery - 380 X 380',
    DEFAULTCROPS: 'Get Default Crops',
    DELETEBUTTON: 'Delete',
    NO_IMAGES: 'No Images found.',
    UPLOAD: 'Upload',
    INFO_TEXT: 'Info',
    INFO1: 'Cropper is an online tool to crop your images',
    INFO2: 'Cropper allows you to free-crop your images, alternatively, you can get 4 default crops, which are, Horizontal, Verical, Horizontal small and Gallery',
    INFO3: 'You can upload only files that are 1024 X 1024 in dimension',
    INFO4: 'File types allowed are : jpg, jpeg and png',
    INFO5: 'File size has to be lower than 5MB',
    INFO6: 'Images can be uploaded to our cloud and can be viewed from any device',
    INFO7: 'Images can be deleted from cloud if you wish to!',
    INFO8: 'Developed by Shrikanth P S - shrikanthps02@gmail.com'
}